# fly.toml app configuration file generated for todaily on 2024-03-17T17:56:34-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "todaily"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile"
  build-target = "build-release-stage"

[env]
  PORT = "4700"

[http_service]
  internal_port = 4700
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
